apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: event-platform
  labels:
    app: ingestion-service
spec:
  type: ClusterIP
  selector:
    app: ingestion-service
  ports:
    - name: health
      port: 8080
      targetPort: 8080
