apiVersion: v1
kind: Service
metadata:
  name: surges-entry-notification
  namespace: surges-entry
  labels:
    app: surges-entry-notification
spec:
  type: ClusterIP
  selector:
    app: surges-entry-notification
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
    - name: health
      port: 8080
      targetPort: 8080
