apiVersion: v1
kind: Service
metadata:
  name: surges-entry-processing
  namespace: surges-entry
  labels:
    app: surges-entry-processing
spec:
  type: ClusterIP
  selector:
    app: surges-entry-processing
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: health
      port: 8080
      targetPort: 8080
